image: Visual Studio 2019 Preview
build_script:
- ps: >-
    dotnet build BasicFodyAddin --configuration Release

    dotnet test BasicFodyAddin --configuration Release --no-build --no-restore
test: off
artifacts:
- path: nugets\*.nupkg